In [1]:
!pip install numpy

In [1]:
import numpy as np

In [5]:
np.__version__

'2.3.5'

In [6]:
# creating 3-dim array using 3 lists
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]
arr_list1_3 = np.array([[list1, list2, list3]])
print(arr_list1_3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [7]:
print(arr_list1_3.ndim)

3


In [9]:
# 1D Attributes
arr_1=np.array([1,2,3])
print(arr_1)


[1 2 3]


In [11]:
print("Shape",arr_1.shape)
print("Size",arr_1.size)
print("dType",arr_1.dtype)
print("n_dim",arr_1.ndim)

Shape (3,)
Size 3
dType int64
n_dim 1


In [15]:
# 3D Attributes
arr_3=np.array([[[0.1,2,3],[4,5,6],[7,8,9]]])
print(arr_3)

[[[0.1 2.  3. ]
  [4.  5.  6. ]
  [7.  8.  9. ]]]


In [16]:
print("Shape",arr_3.shape)
print("Size",arr_3.size)
print("dType",arr_3.dtype)
print("n_dim",arr_3.ndim)

Shape (1, 3, 3)
Size 9
dType float64
n_dim 3


In [1]:
list1 = [1,2,3]
print(list1)

[1, 2, 3]


In [4]:
arr_list1 = np.array(list1) # creating array using list
print(arr_list1)


[1 2 3]


In [5]:
print(type(arr_list1))  # check data type of variable

<class 'numpy.ndarray'>


In [6]:

arr1 = np.array([[1,2,3], [4,5,6]])
print(arr1)


[[1 2 3]
 [4 5 6]]


In [8]:
# Attributes of Array (properties of array)
print("Shape", arr1.shape)  # share= rows, columns and height of array
print("Size", arr1.size)    # number of elements in array
print("dType", arr1.dtype)  # data type of elements in array
print("n_dim", arr1.ndim)   # dimension of array
print("Itemsize",arr1.itemsize) # Memory size of each element (bytes)

Shape (2, 3)
Size 6
dType int64
n_dim 2
Itemsize 8


In [9]:
ones_arr = np.ones((2, 3)) # 2x3 matrix of ones
print(ones_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
empty_arr = np.empty((2,2)) # Creates an uninitialized array (values are random)
print(empty_arr)


[[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 1.69761995e-312]]


In [2]:
a = np.array([1,3,5,7,9])
print(a)
# Slicing :
# array[start:stop:step]
# stop - index, that is not included in output

[1 3 5 7 9]


In [3]:
print(a[1:4]) # Middle 3 elements

[3 5 7]


In [4]:
print(a[0::3]) # Middle 3 elements with steps

[1 7]


In [5]:
print(a[0::2]) # All alternative elements with steps

[1 5 9]
